---
# Playbook to learn through URL and APIs using GitHub APIs
- hosts: localhost
  connection: ssh
  gather_facts: yes
  vars_files:
  - vars.yml
  tasks:
  - name: Get list of repos
    uri:
      url: "https://api.github.com/orgs/LinuxLibrary"
      headers:
        Content-Type: application/json
        Authorization: "Api-Token bc8b36ad2eb983d5018cc9dda589a31ad011843c"
      method: GET
      #force_basic_auth: false
      #body_format: json
      #return_content: true
      timeout: 60
    register: ghout

  - debug:
      var: item
    with_items:
    - "Site Name: {{ ghout.json.login }}"
    - "Site Url: {{ ghout.json.blog }}"
    - "Total Repos: {{ ghout.json.public_repos }}"

  - name: Set URL variable
    set_fact:
      agClusterApi: "ag_cluster_api_{{ dtm_cluster|lower }}"

  - set_fact:
      agBaseUrl: "{{ agClusterApi }}.split('/psg')[0] + '/api/cluster/v2/activeGates?hostname={{ ansible_hostname }}'"

  - set_fact:
      agApiUrl: "{{ agBaseUrl }}"

#  - set_fact:
#      agApiUrlList: "agApiUrlList + "

  - debug:
      var: "{{ agBaseUrl }}"
