---
- hosts: all
  remote_user: jenkins
  become: yes
  become_user: root
  tasks:
  - name: PRE-REQs | Install required packages
    yum: name={{ item }} state=latest
    with_items:
    - git
    - python
    - net-tools
- hosts: control01
  remote_user: jenkins
  become: yes
  become_user: root
  roles:
  - { role: ha-proxy }
- hosts: web-nodes
  remote_user: jenkins
  become: yes
  become_user: root
  roles:
  - { role: nginx }
- hosts: control01
  remote_user: jenkins
  become: yes
  become_user: root
  tasks:
  - name: Verify LoadBalancing
    shell: for i in {1..3}; do curl 192.168.1.50; done
    register: result
  - debug: var=result["stdout"]
